name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 19
        uses: actions/setup-node@v2
        with:
          node-version: "19.1.0"
          cache: "yarn"
      - run: yarn install --immutable
      - run: yarn test && yarn test-deferred
